# Generated by Django 4.0.3 on 2023-04-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nserie', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('tipoEquipo', models.CharField(max_length=20)),
                ('fechaAdquisicion', models.DateTimeField()),
                ('fechaPuestaMarcha', models.DateTimeField()),
                ('provNombre', models.CharField(max_length=30)),
                ('provTelefono', models.IntegerField(default=0)),
                ('planta', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NivelUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nref', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50)),
                ('fechaApertura', models.DateTimeField()),
                ('fechaResolucion', models.DateTimeField()),
                ('empleadoticket', models.CharField(max_length=15)),
                ('cometarios', models.CharField(max_length=40)),
                ('estadoTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.estadoticket')),
                ('nivelUrgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.nivelurgencia')),
                ('tipoTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.tipoticket')),
            ],
        ),
    ]
