# Generated by Django 4.0.3 on 2023-04-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='tipoEquipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='estadoTicket',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='tipoTicket',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='empleadoticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='empleado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppWeb.empleado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='equipo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppWeb.equipo'),
        ),
    ]
