# Generated by Django 4.0.3 on 2023-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0002_rename_tipoequipo_equipo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fechaAdquisicion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fechaPuestaMarcha',
            field=models.DateField(),
        ),
    ]
