# Generated by Django 4.0.3 on 2023-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_alter_equipo_fechaadquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechaApertura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fechaResolucion',
            field=models.DateField(),
        ),
    ]
