# Generated by Django 4.0.3 on 2023-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0004_alter_ticket_fechaapertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fechaAdquisicion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fechaPuestaMarcha',
            field=models.DateTimeField(),
        ),
    ]
