# Generated by Django 4.0.3 on 2023-04-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0006_alter_equipo_fechaadquisicion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='cometarios',
            new_name='comentarios',
        ),
    ]
