# Generated by Django 4.0.3 on 2023-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0007_rename_cometarios_ticket_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nserie',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nref',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
